//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace erablue_resort更新アプリ {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("erablue_resort更新アプリ.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   すべての更新を完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Allok {
            get {
                return ResourceManager.GetString("Allok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリをダウンロード中: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadMessage {
            get {
                return ResourceManager.GetString("DownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新データの取得が完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string downloadok {
            get {
                return ResourceManager.GetString("downloadok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同期処理中にエラーが発生しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exceptionerror1 {
            get {
                return ResourceManager.GetString("Exceptionerror1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    を確認し、必要に応じて削除してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exceptionerror2 {
            get {
                return ResourceManager.GetString("Exceptionerror2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新前のフォルダを削除しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Floderdel {
            get {
                return ResourceManager.GetString("Floderdel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を退避から復元しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string folderload {
            get {
                return ResourceManager.GetString("folderload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を最新版で上書きしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string folderoverwrite {
            get {
                return ResourceManager.GetString("folderoverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を退避しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string foldersave {
            get {
                return ResourceManager.GetString("foldersave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同期処理を開始します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string startnew {
            get {
                return ResourceManager.GetString("startnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一時ディレクトリの削除に失敗しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tempDirerror1 {
            get {
                return ResourceManager.GetString("tempDirerror1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手動で削除してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tempDirerror2 {
            get {
                return ResourceManager.GetString("tempDirerror2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一時ディレクトリを削除しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tempDirok {
            get {
                return ResourceManager.GetString("tempDirok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリURLはGitHubの形式である必要があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URLerror {
            get {
                return ResourceManager.GetString("URLerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。問題のあるフォルダを消してリトライしてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string writeerror {
            get {
                return ResourceManager.GetString("writeerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIPファイルを展開中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zipopen {
            get {
                return ResourceManager.GetString("zipopen", resourceCulture);
            }
        }
    }
}
